/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portaldeacessibilidade;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;

/**
 *
 * @author lucas
 */
public class IshiharaResultNegativo extends javax.swing.JPanel {
    public JDesktopPane jDesktopPane;

    public IshiharaResultNegativo(JDesktopPane jDesktop) {
        initComponents();
        this.jDesktopPane = jDesktop;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width,screenSize.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        btnVoltarMenu2 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        lblResultado.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblResultado.setText("RESULTADO");
        jPanel1.add(lblResultado);
        lblResultado.setBounds(520, 70, 300, 40);

        lblTexto1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblTexto1.setText("O paciente não possui Daltonismo");
        jPanel1.add(lblTexto1);
        lblTexto1.setBounds(280, 270, 800, 56);

        lblTexto2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblTexto2.setText("Não esqueça de realizar todos os testes utilizando o botão abaixo!");
        jPanel1.add(lblTexto2);
        lblTexto2.setBounds(150, 470, 1070, 40);

        btnVoltarMenu2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltarMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/flat-buttons_1_.png"))); // NOI18N
        btnVoltarMenu2.setText("Voltar ao menu Principal");
        btnVoltarMenu2.setBorder(null);
        btnVoltarMenu2.setBorderPainted(false);
        btnVoltarMenu2.setContentAreaFilled(false);
        btnVoltarMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltarMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenu2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarMenu2);
        btnVoltarMenu2.setBounds(530, 550, 250, 60);
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenu2ActionPerformed
        jDesktopPane.removeAll();
        MenuPrincipal TelaTeste = new MenuPrincipal(jDesktopPane);
        TelaTeste.setVisible(true);
        jDesktopPane.add(TelaTeste);
    }//GEN-LAST:event_btnVoltarMenu2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    // End of variables declaration//GEN-END:variables
}
