/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portaldeacessibilidade;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;

/**
 *
 * @author lucas
 */
public class IshiharaResuDeuteranopia extends javax.swing.JPanel {
    public JDesktopPane jDesktopPane;
    
    public IshiharaResuDeuteranopia(JDesktopPane jDesktop) {
        initComponents();
        this.jDesktopPane = jDesktop;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width,screenSize.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblResultado2 = new javax.swing.JLabel();
        btnVoltarMenu2 = new javax.swing.JButton();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel3.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.setLayout(null);

        lblResultado2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblResultado2.setText("RESULTADO");
        jPanel3.add(lblResultado2);
        lblResultado2.setBounds(520, 70, 300, 40);

        btnVoltarMenu2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltarMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/flat-buttons_1_.png"))); // NOI18N
        btnVoltarMenu2.setText("Voltar ao menu Principal");
        btnVoltarMenu2.setBorder(null);
        btnVoltarMenu2.setBorderPainted(false);
        btnVoltarMenu2.setContentAreaFilled(false);
        btnVoltarMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltarMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenu2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltarMenu2);
        btnVoltarMenu2.setBounds(530, 550, 250, 60);

        lblTexto1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblTexto1.setText("O paciente possui um grau de Daltonismo");
        jPanel3.add(lblTexto1);
        lblTexto1.setBounds(210, 220, 940, 56);

        lblTexto2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblTexto2.setText("Recomendamos que o paciente procure um oftalmologista");
        jPanel3.add(lblTexto2);
        lblTexto2.setBounds(190, 290, 950, 60);

        lblTexto3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblTexto3.setText("Não esqueça de realizar todos os testes utilizando o botão abaixo!");
        jPanel3.add(lblTexto3);
        lblTexto3.setBounds(150, 470, 1070, 40);
        jPanel3.add(lblBackground);
        lblBackground.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenu2ActionPerformed
        jDesktopPane.removeAll();
        MenuPrincipal TelaTeste = new MenuPrincipal(jDesktopPane);
        TelaTeste.setVisible(true);
        jDesktopPane.add(TelaTeste);
    }//GEN-LAST:event_btnVoltarMenu2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarMenu2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblResultado2;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    // End of variables declaration//GEN-END:variables
}
